services:
  web:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.https.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/certs/smartzhima:/etc/nginx/certs:ro
    networks:
      - default
      - web-edge

networks:
  web-edge:
    external: true
