server {
    listen 80;
    server_name smartzhima.com www.smartzhima.com *.smartzhima.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name math-staging-api.smartzhima.com;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        resolver 127.0.0.11 valid=30s ipv6=off;
        set $math_game_staging http://math-game-staging-api;
        proxy_pass $math_game_staging;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 3m;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name math-api.smartzhima.com;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        resolver 127.0.0.11 valid=30s ipv6=off;
        set $math_game_prod http://math-game-prod-api;
        proxy_pass $math_game_prod;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 3m;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name smartzhima.com www.smartzhima.com *.smartzhima.com;

    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:css|js|svg|png|jpg|jpeg|gif|webp|ico)$ {
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
